/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BodyPart {
    #[serde(rename = "contentDisposition", skip_serializing_if = "Option::is_none")]
    pub content_disposition: Option<crate::models::ContentDisposition>,
    #[serde(rename = "entity", skip_serializing_if = "Option::is_none")]
    pub entity: Option<serde_json::Value>,
    #[serde(rename = "headers", skip_serializing_if = "Option::is_none")]
    pub headers: Option<::std::collections::HashMap<String, Vec<String>>>,
    #[serde(rename = "mediaType", skip_serializing_if = "Option::is_none")]
    pub media_type: Option<crate::models::BodyPartMediaType>,
    #[serde(rename = "messageBodyWorkers", skip_serializing_if = "Option::is_none")]
    pub message_body_workers: Option<serde_json::Value>,
    #[serde(rename = "parent", skip_serializing_if = "Option::is_none")]
    pub parent: Option<crate::models::MultiPart>,
    #[serde(rename = "providers", skip_serializing_if = "Option::is_none")]
    pub providers: Option<serde_json::Value>,
    #[serde(rename = "parameterizedHeaders", skip_serializing_if = "Option::is_none")]
    pub parameterized_headers: Option<::std::collections::HashMap<String, Vec<crate::models::ParameterizedHeader>>>,
}

impl BodyPart {
    pub fn new() -> BodyPart {
        BodyPart {
            content_disposition: None,
            entity: None,
            headers: None,
            media_type: None,
            message_body_workers: None,
            parent: None,
            providers: None,
            parameterized_headers: None,
        }
    }
}


