/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtAppElementCommitTransactionParams {
    #[serde(rename = "transactionId", skip_serializing_if = "Option::is_none")]
    pub transaction_id: Option<String>,
    #[serde(rename = "returnError", skip_serializing_if = "Option::is_none")]
    pub return_error: Option<bool>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl BtAppElementCommitTransactionParams {
    pub fn new() -> BtAppElementCommitTransactionParams {
        BtAppElementCommitTransactionParams {
            transaction_id: None,
            return_error: None,
            description: None,
        }
    }
}


