/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtAppElementChangeParams {
    #[serde(rename = "subelementId", skip_serializing_if = "Option::is_none")]
    pub subelement_id: Option<String>,
    #[serde(rename = "baseContent", skip_serializing_if = "Option::is_none")]
    pub base_content: Option<String>,
    #[serde(rename = "delta", skip_serializing_if = "Option::is_none")]
    pub delta: Option<String>,
}

impl BtAppElementChangeParams {
    pub fn new() -> BtAppElementChangeParams {
        BtAppElementChangeParams {
            subelement_id: None,
            base_content: None,
            delta: None,
        }
    }
}


