/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtAclParams {
    #[serde(rename = "documentId", skip_serializing_if = "Option::is_none")]
    pub document_id: Option<String>,
    #[serde(rename = "anonymousAccessAllowed", skip_serializing_if = "Option::is_none")]
    pub anonymous_access_allowed: Option<bool>,
    #[serde(rename = "anonymousAllowsExport", skip_serializing_if = "Option::is_none")]
    pub anonymous_allows_export: Option<bool>,
    #[serde(rename = "public", skip_serializing_if = "Option::is_none")]
    pub public: Option<bool>,
}

impl BtAclParams {
    pub fn new() -> BtAclParams {
        BtAclParams {
            document_id: None,
            anonymous_access_allowed: None,
            anonymous_allows_export: None,
            public: None,
        }
    }
}


