/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtAppElementUpdateParams {
    #[serde(rename = "changes", skip_serializing_if = "Option::is_none")]
    pub changes: Option<Vec<crate::models::BtAppElementChangeParams>>,
    #[serde(rename = "transactionId", skip_serializing_if = "Option::is_none")]
    pub transaction_id: Option<String>,
    #[serde(rename = "parentChangeId", skip_serializing_if = "Option::is_none")]
    pub parent_change_id: Option<String>,
    #[serde(rename = "returnError", skip_serializing_if = "Option::is_none")]
    pub return_error: Option<bool>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl BtAppElementUpdateParams {
    pub fn new() -> BtAppElementUpdateParams {
        BtAppElementUpdateParams {
            changes: None,
            transaction_id: None,
            parent_change_id: None,
            return_error: None,
            description: None,
        }
    }
}


