/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtAppElementContentEntryInfo {
    #[serde(rename = "subelementId", skip_serializing_if = "Option::is_none")]
    pub subelement_id: Option<String>,
    #[serde(rename = "baseContent", skip_serializing_if = "Option::is_none")]
    pub base_content: Option<String>,
    #[serde(rename = "deltas", skip_serializing_if = "Option::is_none")]
    pub deltas: Option<Vec<crate::models::BtAppElementContentDeltaInfo>>,
}

impl BtAppElementContentEntryInfo {
    pub fn new() -> BtAppElementContentEntryInfo {
        BtAppElementContentEntryInfo {
            subelement_id: None,
            base_content: None,
            deltas: None,
        }
    }
}


