/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtAppElementStartTransactionParams {
    #[serde(rename = "parentChangeId", skip_serializing_if = "Option::is_none")]
    pub parent_change_id: Option<String>,
    #[serde(rename = "returnError", skip_serializing_if = "Option::is_none")]
    pub return_error: Option<bool>,
}

impl BtAppElementStartTransactionParams {
    pub fn new() -> BtAppElementStartTransactionParams {
        BtAppElementStartTransactionParams {
            parent_change_id: None,
            return_error: None,
        }
    }
}


