/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtAssemblyTransformDefinitionParams {
    #[serde(rename = "transform", skip_serializing_if = "Option::is_none")]
    pub transform: Option<Vec<f64>>,
    #[serde(rename = "occurrences", skip_serializing_if = "Option::is_none")]
    pub occurrences: Option<Vec<crate::models::BtOccurrence>>,
    #[serde(rename = "isRelative", skip_serializing_if = "Option::is_none")]
    pub is_relative: Option<bool>,
}

impl BtAssemblyTransformDefinitionParams {
    pub fn new() -> BtAssemblyTransformDefinitionParams {
        BtAssemblyTransformDefinitionParams {
            transform: None,
            occurrences: None,
            is_relative: None,
        }
    }
}


