/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtAppElementReferenceParams {
    #[serde(rename = "partNumber", skip_serializing_if = "Option::is_none")]
    pub part_number: Option<String>,
    #[serde(rename = "transactionId", skip_serializing_if = "Option::is_none")]
    pub transaction_id: Option<String>,
    #[serde(rename = "parentChangeId", skip_serializing_if = "Option::is_none")]
    pub parent_change_id: Option<String>,
    #[serde(rename = "revision", skip_serializing_if = "Option::is_none")]
    pub revision: Option<String>,
    #[serde(rename = "idTag", skip_serializing_if = "Option::is_none")]
    pub id_tag: Option<String>,
    #[serde(rename = "targetDocumentId", skip_serializing_if = "Option::is_none")]
    pub target_document_id: Option<String>,
    #[serde(rename = "targetElementId", skip_serializing_if = "Option::is_none")]
    pub target_element_id: Option<String>,
    #[serde(rename = "targetConfiguration", skip_serializing_if = "Option::is_none")]
    pub target_configuration: Option<String>,
    #[serde(rename = "sketchIds", skip_serializing_if = "Option::is_none")]
    pub sketch_ids: Option<Vec<String>>,
    #[serde(rename = "targetVersionId", skip_serializing_if = "Option::is_none")]
    pub target_version_id: Option<String>,
    #[serde(rename = "pureSketch", skip_serializing_if = "Option::is_none")]
    pub pure_sketch: Option<bool>,
    #[serde(rename = "isSketchOnly", skip_serializing_if = "Option::is_none")]
    pub is_sketch_only: Option<bool>,
    #[serde(rename = "returnError", skip_serializing_if = "Option::is_none")]
    pub return_error: Option<bool>,
    #[serde(rename = "hasDocumentMicroversions", skip_serializing_if = "Option::is_none")]
    pub has_document_microversions: Option<bool>,
    #[serde(rename = "targetMicroversionId", skip_serializing_if = "Option::is_none")]
    pub target_microversion_id: Option<String>,
    #[serde(rename = "idTagMicroversionId", skip_serializing_if = "Option::is_none")]
    pub id_tag_microversion_id: Option<String>,
    #[serde(rename = "trackNewVersions", skip_serializing_if = "Option::is_none")]
    pub track_new_versions: Option<bool>,
    #[serde(rename = "updateSketchInfo", skip_serializing_if = "Option::is_none")]
    pub update_sketch_info: Option<bool>,
    #[serde(rename = "referenceType", skip_serializing_if = "Option::is_none")]
    pub reference_type: Option<i32>,
}

impl BtAppElementReferenceParams {
    pub fn new() -> BtAppElementReferenceParams {
        BtAppElementReferenceParams {
            part_number: None,
            transaction_id: None,
            parent_change_id: None,
            revision: None,
            id_tag: None,
            target_document_id: None,
            target_element_id: None,
            target_configuration: None,
            sketch_ids: None,
            target_version_id: None,
            pure_sketch: None,
            is_sketch_only: None,
            return_error: None,
            has_document_microversions: None,
            target_microversion_id: None,
            id_tag_microversion_id: None,
            track_new_versions: None,
            update_sketch_info: None,
            reference_type: None,
        }
    }
}


