/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtAutoPartNumberingSchemeParams {
    #[serde(rename = "assemblyPrefix", skip_serializing_if = "Option::is_none")]
    pub assembly_prefix: Option<String>,
    #[serde(rename = "drawingPrefix", skip_serializing_if = "Option::is_none")]
    pub drawing_prefix: Option<String>,
    #[serde(rename = "filePrefix", skip_serializing_if = "Option::is_none")]
    pub file_prefix: Option<String>,
    #[serde(rename = "partPrefix", skip_serializing_if = "Option::is_none")]
    pub part_prefix: Option<String>,
    #[serde(rename = "nextNumber", skip_serializing_if = "Option::is_none")]
    pub next_number: Option<i64>,
    #[serde(rename = "nextNumberMinWidth", skip_serializing_if = "Option::is_none")]
    pub next_number_min_width: Option<i32>,
    #[serde(rename = "schemeId", skip_serializing_if = "Option::is_none")]
    pub scheme_id: Option<String>,
}

impl BtAutoPartNumberingSchemeParams {
    pub fn new() -> BtAutoPartNumberingSchemeParams {
        BtAutoPartNumberingSchemeParams {
            assembly_prefix: None,
            drawing_prefix: None,
            file_prefix: None,
            part_prefix: None,
            next_number: None,
            next_number_min_width: None,
            scheme_id: None,
        }
    }
}


