/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtAssemblyInstanceDefinitionParams {
    #[serde(rename = "configuration", skip_serializing_if = "Option::is_none")]
    pub configuration: Option<String>,
    #[serde(rename = "versionId", skip_serializing_if = "Option::is_none")]
    pub version_id: Option<String>,
    #[serde(rename = "elementId", skip_serializing_if = "Option::is_none")]
    pub element_id: Option<String>,
    #[serde(rename = "documentId", skip_serializing_if = "Option::is_none")]
    pub document_id: Option<String>,
    #[serde(rename = "microversionId", skip_serializing_if = "Option::is_none")]
    pub microversion_id: Option<String>,
    #[serde(rename = "partNumber", skip_serializing_if = "Option::is_none")]
    pub part_number: Option<String>,
    #[serde(rename = "revision", skip_serializing_if = "Option::is_none")]
    pub revision: Option<String>,
    #[serde(rename = "partId", skip_serializing_if = "Option::is_none")]
    pub part_id: Option<String>,
    #[serde(rename = "featureId", skip_serializing_if = "Option::is_none")]
    pub feature_id: Option<String>,
    #[serde(rename = "isAssembly", skip_serializing_if = "Option::is_none")]
    pub is_assembly: Option<bool>,
    #[serde(rename = "isWholePartStudio", skip_serializing_if = "Option::is_none")]
    pub is_whole_part_studio: Option<bool>,
}

impl BtAssemblyInstanceDefinitionParams {
    pub fn new() -> BtAssemblyInstanceDefinitionParams {
        BtAssemblyInstanceDefinitionParams {
            configuration: None,
            version_id: None,
            element_id: None,
            document_id: None,
            microversion_id: None,
            part_number: None,
            revision: None,
            part_id: None,
            feature_id: None,
            is_assembly: None,
            is_whole_part_studio: None,
        }
    }
}


