/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtBoundingBox {
    #[serde(rename = "valid", skip_serializing_if = "Option::is_none")]
    pub valid: Option<bool>,
    #[serde(rename = "minCorner", skip_serializing_if = "Option::is_none")]
    pub min_corner: Option<crate::models::BtVector3d>,
    #[serde(rename = "maxCorner", skip_serializing_if = "Option::is_none")]
    pub max_corner: Option<crate::models::BtVector3d>,
}

impl BtBoundingBox {
    pub fn new() -> BtBoundingBox {
        BtBoundingBox {
            valid: None,
            min_corner: None,
            max_corner: None,
        }
    }
}


