/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtBetaCapabilityAdminInfo {
    #[serde(rename = "approvalsPerHour", skip_serializing_if = "Option::is_none")]
    pub approvals_per_hour: Option<f64>,
    #[serde(rename = "autoApprove", skip_serializing_if = "Option::is_none")]
    pub auto_approve: Option<bool>,
    #[serde(rename = "autoApprovePaid", skip_serializing_if = "Option::is_none")]
    pub auto_approve_paid: Option<bool>,
    #[serde(rename = "autoApproveOnshape", skip_serializing_if = "Option::is_none")]
    pub auto_approve_onshape: Option<bool>,
    #[serde(rename = "selfServiceDisabled", skip_serializing_if = "Option::is_none")]
    pub self_service_disabled: Option<bool>,
    #[serde(rename = "userCount", skip_serializing_if = "Option::is_none")]
    pub user_count: Option<i32>,
    #[serde(rename = "userLimit", skip_serializing_if = "Option::is_none")]
    pub user_limit: Option<i32>,
    #[serde(rename = "capabilityName", skip_serializing_if = "Option::is_none")]
    pub capability_name: Option<String>,
    #[serde(rename = "eula", skip_serializing_if = "Option::is_none")]
    pub eula: Option<String>,
    #[serde(rename = "welcomeHTML", skip_serializing_if = "Option::is_none")]
    pub welcome_html: Option<String>,
    #[serde(rename = "userState", skip_serializing_if = "Option::is_none")]
    pub user_state: Option<i32>,
    #[serde(rename = "upgradable", skip_serializing_if = "Option::is_none")]
    pub upgradable: Option<bool>,
    #[serde(rename = "userBased", skip_serializing_if = "Option::is_none")]
    pub user_based: Option<bool>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "href", skip_serializing_if = "Option::is_none")]
    pub href: Option<String>,
    #[serde(rename = "viewRef", skip_serializing_if = "Option::is_none")]
    pub view_ref: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

impl BtBetaCapabilityAdminInfo {
    pub fn new() -> BtBetaCapabilityAdminInfo {
        BtBetaCapabilityAdminInfo {
            approvals_per_hour: None,
            auto_approve: None,
            auto_approve_paid: None,
            auto_approve_onshape: None,
            self_service_disabled: None,
            user_count: None,
            user_limit: None,
            capability_name: None,
            eula: None,
            welcome_html: None,
            user_state: None,
            upgradable: None,
            user_based: None,
            description: None,
            href: None,
            view_ref: None,
            name: None,
            id: None,
        }
    }
}


