/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtBillingPlanInfo {
    #[serde(rename = "trialPeriodDays", skip_serializing_if = "Option::is_none")]
    pub trial_period_days: Option<i32>,
    #[serde(rename = "group", skip_serializing_if = "Option::is_none")]
    pub group: Option<String>,
    #[serde(rename = "clientId", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    #[serde(rename = "discountInfo", skip_serializing_if = "Option::is_none")]
    pub discount_info: Option<crate::models::BtDiscountInfo>,
    #[serde(rename = "onshapePlan", skip_serializing_if = "Option::is_none")]
    pub onshape_plan: Option<bool>,
    #[serde(rename = "applicationId", skip_serializing_if = "Option::is_none")]
    pub application_id: Option<String>,
    #[serde(rename = "deprecated", skip_serializing_if = "Option::is_none")]
    pub deprecated: Option<bool>,
    #[serde(rename = "planType", skip_serializing_if = "Option::is_none")]
    pub plan_type: Option<i32>,
    #[serde(rename = "consumableQuantity", skip_serializing_if = "Option::is_none")]
    pub consumable_quantity: Option<i32>,
    #[serde(rename = "amountCents", skip_serializing_if = "Option::is_none")]
    pub amount_cents: Option<i32>,
    #[serde(rename = "interval", skip_serializing_if = "Option::is_none")]
    pub interval: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "companyPlan", skip_serializing_if = "Option::is_none")]
    pub company_plan: Option<bool>,
    #[serde(rename = "hidden", skip_serializing_if = "Option::is_none")]
    pub hidden: Option<bool>,
    #[serde(rename = "href", skip_serializing_if = "Option::is_none")]
    pub href: Option<String>,
    #[serde(rename = "viewRef", skip_serializing_if = "Option::is_none")]
    pub view_ref: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

impl BtBillingPlanInfo {
    pub fn new() -> BtBillingPlanInfo {
        BtBillingPlanInfo {
            trial_period_days: None,
            group: None,
            client_id: None,
            discount_info: None,
            onshape_plan: None,
            application_id: None,
            deprecated: None,
            plan_type: None,
            consumable_quantity: None,
            amount_cents: None,
            interval: None,
            description: None,
            company_plan: None,
            hidden: None,
            href: None,
            view_ref: None,
            name: None,
            id: None,
        }
    }
}


