/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtBulkDocumentUpdateParams {
    #[serde(rename = "documentIds", skip_serializing_if = "Option::is_none")]
    pub document_ids: Option<String>,
    #[serde(rename = "updateProperty", skip_serializing_if = "Option::is_none")]
    pub update_property: Option<String>,
    #[serde(rename = "skipUpgradeVersion", skip_serializing_if = "Option::is_none")]
    pub skip_upgrade_version: Option<i32>,
    #[serde(rename = "skipUpgrade", skip_serializing_if = "Option::is_none")]
    pub skip_upgrade: Option<bool>,
    #[serde(rename = "upgradeMode", skip_serializing_if = "Option::is_none")]
    pub upgrade_mode: Option<String>,
    #[serde(rename = "upgradeVersion", skip_serializing_if = "Option::is_none")]
    pub upgrade_version: Option<i32>,
}

impl BtBulkDocumentUpdateParams {
    pub fn new() -> BtBulkDocumentUpdateParams {
        BtBulkDocumentUpdateParams {
            document_ids: None,
            update_property: None,
            skip_upgrade_version: None,
            skip_upgrade: None,
            upgrade_mode: None,
            upgrade_version: None,
        }
    }
}


