/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtComponentUsagesSummary {
    #[serde(rename = "hierarchy_", skip_serializing_if = "Option::is_none")]
    pub hierarchy_: Option<crate::models::BtStandardContentHierarchy>,
    #[serde(rename = "hierarchy", skip_serializing_if = "Option::is_none")]
    pub hierarchy: Option<crate::models::BtStandardContentHierarchy>,
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i64>,
}

impl BtComponentUsagesSummary {
    pub fn new() -> BtComponentUsagesSummary {
        BtComponentUsagesSummary {
            hierarchy_: None,
            hierarchy: None,
            count: None,
        }
    }
}


