/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtCommentParams {
    #[serde(rename = "elementQuery", skip_serializing_if = "Option::is_none")]
    pub element_query: Option<String>,
    #[serde(rename = "elementFeature", skip_serializing_if = "Option::is_none")]
    pub element_feature: Option<String>,
    #[serde(rename = "elementOccurrence", skip_serializing_if = "Option::is_none")]
    pub element_occurrence: Option<String>,
    #[serde(rename = "assemblyFeature", skip_serializing_if = "Option::is_none")]
    pub assembly_feature: Option<String>,
    #[serde(rename = "versionId", skip_serializing_if = "Option::is_none")]
    pub version_id: Option<String>,
    #[serde(rename = "workspaceId", skip_serializing_if = "Option::is_none")]
    pub workspace_id: Option<String>,
    #[serde(rename = "elementId", skip_serializing_if = "Option::is_none")]
    pub element_id: Option<String>,
    #[serde(rename = "documentId", skip_serializing_if = "Option::is_none")]
    pub document_id: Option<String>,
    #[serde(rename = "parentId", skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<String>,
    #[serde(rename = "assignee", skip_serializing_if = "Option::is_none")]
    pub assignee: Option<String>,
    #[serde(rename = "viewData", skip_serializing_if = "Option::is_none")]
    pub view_data: Option<crate::models::BtViewDataParams>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

impl BtCommentParams {
    pub fn new() -> BtCommentParams {
        BtCommentParams {
            element_query: None,
            element_feature: None,
            element_occurrence: None,
            assembly_feature: None,
            version_id: None,
            workspace_id: None,
            element_id: None,
            document_id: None,
            parent_id: None,
            assignee: None,
            view_data: None,
            message: None,
            id: None,
        }
    }
}


