/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtCreateCustomToolParams {
    #[serde(rename = "insertableId", skip_serializing_if = "Option::is_none")]
    pub insertable_id: Option<String>,
    #[serde(rename = "tool", skip_serializing_if = "Option::is_none")]
    pub tool: Option<crate::models::BtToolTreeParams>,
}

impl BtCreateCustomToolParams {
    pub fn new() -> BtCreateCustomToolParams {
        BtCreateCustomToolParams {
            insertable_id: None,
            tool: None,
        }
    }
}


