/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtCurveDescription {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<Type>,
}

impl BtCurveDescription {
    pub fn new() -> BtCurveDescription {
        BtCurveDescription {
            _type: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "OTHER")]
    OTHER,
    #[serde(rename = "LINE")]
    LINE,
    #[serde(rename = "CIRCLE")]
    CIRCLE,
    #[serde(rename = "ELLIPSE")]
    ELLIPSE,
    #[serde(rename = "BCURVE")]
    BCURVE,
    #[serde(rename = "ICURVE")]
    ICURVE,
    #[serde(rename = "UNKNOWN")]
    UNKNOWN,
}

