/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtCloudStorageAccountInfoAllOf {
    #[serde(rename = "cloudStorageAccountId_", skip_serializing_if = "Option::is_none")]
    pub cloud_storage_account_id_: Option<String>,
    #[serde(rename = "cloudStorageAccountId", skip_serializing_if = "Option::is_none")]
    pub cloud_storage_account_id: Option<String>,
    #[serde(rename = "importFolder", skip_serializing_if = "Option::is_none")]
    pub import_folder: Option<crate::models::BtCloudStorageObjectInfo>,
    #[serde(rename = "exportFolder", skip_serializing_if = "Option::is_none")]
    pub export_folder: Option<crate::models::BtCloudStorageObjectInfo>,
    #[serde(rename = "cloudStorageProvider", skip_serializing_if = "Option::is_none")]
    pub cloud_storage_provider: Option<i32>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
}

impl BtCloudStorageAccountInfoAllOf {
    pub fn new() -> BtCloudStorageAccountInfoAllOf {
        BtCloudStorageAccountInfoAllOf {
            cloud_storage_account_id_: None,
            cloud_storage_account_id: None,
            import_folder: None,
            export_folder: None,
            cloud_storage_provider: None,
            enabled: None,
        }
    }
}


