/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtCompanyTransferParams {
    #[serde(rename = "currentOwnerId", skip_serializing_if = "Option::is_none")]
    pub current_owner_id: Option<String>,
    #[serde(rename = "newOwnerId", skip_serializing_if = "Option::is_none")]
    pub new_owner_id: Option<String>,
}

impl BtCompanyTransferParams {
    pub fn new() -> BtCompanyTransferParams {
        BtCompanyTransferParams {
            current_owner_id: None,
            new_owner_id: None,
        }
    }
}


