/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtCompanyPoliciesParams {
    #[serde(rename = "requireTotp", skip_serializing_if = "Option::is_none")]
    pub require_totp: Option<bool>,
    #[serde(rename = "useLightUi", skip_serializing_if = "Option::is_none")]
    pub use_light_ui: Option<bool>,
    #[serde(rename = "integrations", skip_serializing_if = "Option::is_none")]
    pub integrations: Option<crate::models::IntegrationsParams>,
    #[serde(rename = "requireApprovedDrawingTemplates", skip_serializing_if = "Option::is_none")]
    pub require_approved_drawing_templates: Option<bool>,
    #[serde(rename = "approvedDrawingTemplatesDocumentId", skip_serializing_if = "Option::is_none")]
    pub approved_drawing_templates_document_id: Option<String>,
    #[serde(rename = "addCompanyOwnedLibrariesInUserAccount", skip_serializing_if = "Option::is_none")]
    pub add_company_owned_libraries_in_user_account: Option<bool>,
    #[serde(rename = "releaseWorkflowId", skip_serializing_if = "Option::is_none")]
    pub release_workflow_id: Option<String>,
    #[serde(rename = "obsoletionWorkflowId", skip_serializing_if = "Option::is_none")]
    pub obsoletion_workflow_id: Option<String>,
    #[serde(rename = "revisionSchemeId", skip_serializing_if = "Option::is_none")]
    pub revision_scheme_id: Option<String>,
    #[serde(rename = "requireRevisionForReleasedObjects", skip_serializing_if = "Option::is_none")]
    pub require_revision_for_released_objects: Option<bool>,
    #[serde(rename = "requirePartNumberForReleasedObjects", skip_serializing_if = "Option::is_none")]
    pub require_part_number_for_released_objects: Option<bool>,
    #[serde(rename = "onlyAdminsCanEditPropertiesOfReleasedObjects", skip_serializing_if = "Option::is_none")]
    pub only_admins_can_edit_properties_of_released_objects: Option<bool>,
    #[serde(rename = "onlyAdminsCanDeleteDocumentsContainingReleasedObjects", skip_serializing_if = "Option::is_none")]
    pub only_admins_can_delete_documents_containing_released_objects: Option<bool>,
    #[serde(rename = "onlyAdminsCanApproveReleases", skip_serializing_if = "Option::is_none")]
    pub only_admins_can_approve_releases: Option<bool>,
    #[serde(rename = "requirePartsAndSubassembliesReleaseWithAssembly", skip_serializing_if = "Option::is_none")]
    pub require_parts_and_subassemblies_release_with_assembly: Option<bool>,
    #[serde(rename = "requirePartsAndSubassembliesReleaseWithDrawing", skip_serializing_if = "Option::is_none")]
    pub require_parts_and_subassemblies_release_with_drawing: Option<bool>,
    #[serde(rename = "requireBasePartReleaseWithDerivedPart", skip_serializing_if = "Option::is_none")]
    pub require_base_part_release_with_derived_part: Option<bool>,
    #[serde(rename = "requireImageReleaseWithDrawing", skip_serializing_if = "Option::is_none")]
    pub require_image_release_with_drawing: Option<bool>,
    #[serde(rename = "actionShowDrawingsWatermark", skip_serializing_if = "Option::is_none")]
    pub action_show_drawings_watermark: Option<bool>,
    #[serde(rename = "hideWatermarkForNotRevManaged", skip_serializing_if = "Option::is_none")]
    pub hide_watermark_for_not_rev_managed: Option<bool>,
    #[serde(rename = "preventDuplicateDocumentNameRegex", skip_serializing_if = "Option::is_none")]
    pub prevent_duplicate_document_name_regex: Option<String>,
    #[serde(rename = "errorOnFeatureListErrorsDuringRelease", skip_serializing_if = "Option::is_none")]
    pub error_on_feature_list_errors_during_release: Option<bool>,
    #[serde(rename = "errorOnRollbackBarNotAtEndDuringRelease", skip_serializing_if = "Option::is_none")]
    pub error_on_rollback_bar_not_at_end_during_release: Option<bool>,
    #[serde(rename = "errorOnAssemblyTreeErrorsDuringRelease", skip_serializing_if = "Option::is_none")]
    pub error_on_assembly_tree_errors_during_release: Option<bool>,
    #[serde(rename = "errorOnPendingContextEditsDuringRelease", skip_serializing_if = "Option::is_none")]
    pub error_on_pending_context_edits_during_release: Option<bool>,
    #[serde(rename = "errorOnPendingDrawingUpdateDuringRelease", skip_serializing_if = "Option::is_none")]
    pub error_on_pending_drawing_update_during_release: Option<bool>,
    #[serde(rename = "errorOnPendingDanglingDrawingObjectsDuringRelease", skip_serializing_if = "Option::is_none")]
    pub error_on_pending_dangling_drawing_objects_during_release: Option<bool>,
    #[serde(rename = "approverRequiredDuringRelease", skip_serializing_if = "Option::is_none")]
    pub approver_required_during_release: Option<bool>,
    #[serde(rename = "noteRequiredDuringRelease", skip_serializing_if = "Option::is_none")]
    pub note_required_during_release: Option<bool>,
    #[serde(rename = "requireAllApprovers", skip_serializing_if = "Option::is_none")]
    pub require_all_approvers: Option<bool>,
    #[serde(rename = "allowReleaseItemsFromOtherDocuments", skip_serializing_if = "Option::is_none")]
    pub allow_release_items_from_other_documents: Option<bool>,
    #[serde(rename = "automaticallyObsoletePreviousReleasedRevisions", skip_serializing_if = "Option::is_none")]
    pub automatically_obsolete_previous_released_revisions: Option<bool>,
    #[serde(rename = "partNumberingSchemeId", skip_serializing_if = "Option::is_none")]
    pub part_numbering_scheme_id: Option<String>,
    #[serde(rename = "requirePeerReview", skip_serializing_if = "Option::is_none")]
    pub require_peer_review: Option<bool>,
    #[serde(rename = "drawingCanDuplicatePartNumber", skip_serializing_if = "Option::is_none")]
    pub drawing_can_duplicate_part_number: Option<bool>,
    #[serde(rename = "enabledActiveMultipleWorkflows", skip_serializing_if = "Option::is_none")]
    pub enabled_active_multiple_workflows: Option<bool>,
    #[serde(rename = "onlyAdminsCanMarkObjectsAsNotRevisionManaged", skip_serializing_if = "Option::is_none")]
    pub only_admins_can_mark_objects_as_not_revision_managed: Option<bool>,
    #[serde(rename = "useCompanyFeaturesToolbar", skip_serializing_if = "Option::is_none")]
    pub use_company_features_toolbar: Option<bool>,
}

impl BtCompanyPoliciesParams {
    pub fn new() -> BtCompanyPoliciesParams {
        BtCompanyPoliciesParams {
            require_totp: None,
            use_light_ui: None,
            integrations: None,
            require_approved_drawing_templates: None,
            approved_drawing_templates_document_id: None,
            add_company_owned_libraries_in_user_account: None,
            release_workflow_id: None,
            obsoletion_workflow_id: None,
            revision_scheme_id: None,
            require_revision_for_released_objects: None,
            require_part_number_for_released_objects: None,
            only_admins_can_edit_properties_of_released_objects: None,
            only_admins_can_delete_documents_containing_released_objects: None,
            only_admins_can_approve_releases: None,
            require_parts_and_subassemblies_release_with_assembly: None,
            require_parts_and_subassemblies_release_with_drawing: None,
            require_base_part_release_with_derived_part: None,
            require_image_release_with_drawing: None,
            action_show_drawings_watermark: None,
            hide_watermark_for_not_rev_managed: None,
            prevent_duplicate_document_name_regex: None,
            error_on_feature_list_errors_during_release: None,
            error_on_rollback_bar_not_at_end_during_release: None,
            error_on_assembly_tree_errors_during_release: None,
            error_on_pending_context_edits_during_release: None,
            error_on_pending_drawing_update_during_release: None,
            error_on_pending_dangling_drawing_objects_during_release: None,
            approver_required_during_release: None,
            note_required_during_release: None,
            require_all_approvers: None,
            allow_release_items_from_other_documents: None,
            automatically_obsolete_previous_released_revisions: None,
            part_numbering_scheme_id: None,
            require_peer_review: None,
            drawing_can_duplicate_part_number: None,
            enabled_active_multiple_workflows: None,
            only_admins_can_mark_objects_as_not_revision_managed: None,
            use_company_features_toolbar: None,
        }
    }
}


