/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtCopyElementParams {
    #[serde(rename = "documentIdSource", skip_serializing_if = "Option::is_none")]
    pub document_id_source: Option<String>,
    #[serde(rename = "workspaceIdSource", skip_serializing_if = "Option::is_none")]
    pub workspace_id_source: Option<String>,
    #[serde(rename = "elementIdSource", skip_serializing_if = "Option::is_none")]
    pub element_id_source: Option<String>,
    #[serde(rename = "anchorElementId", skip_serializing_if = "Option::is_none")]
    pub anchor_element_id: Option<String>,
    #[serde(rename = "isGroupAnchor", skip_serializing_if = "Option::is_none")]
    pub is_group_anchor: Option<bool>,
}

impl BtCopyElementParams {
    pub fn new() -> BtCopyElementParams {
        BtCopyElementParams {
            document_id_source: None,
            workspace_id_source: None,
            element_id_source: None,
            anchor_element_id: None,
            is_group_anchor: None,
        }
    }
}


