/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtDocumentOptionsParams {
    #[serde(rename = "cppServerMemory", skip_serializing_if = "Option::is_none")]
    pub cpp_server_memory: Option<i32>,
    #[serde(rename = "enableCppServerMemoryDiagnostics", skip_serializing_if = "Option::is_none")]
    pub enable_cpp_server_memory_diagnostics: Option<bool>,
    #[serde(rename = "documentMemory", skip_serializing_if = "Option::is_none")]
    pub document_memory: Option<i32>,
    #[serde(rename = "extendedDisplayCheck", skip_serializing_if = "Option::is_none")]
    pub extended_display_check: Option<bool>,
    #[serde(rename = "cppServerLimit", skip_serializing_if = "Option::is_none")]
    pub cpp_server_limit: Option<i32>,
    #[serde(rename = "thumbnailCppServerLimit", skip_serializing_if = "Option::is_none")]
    pub thumbnail_cpp_server_limit: Option<i32>,
    #[serde(rename = "linkedCppServerLimit", skip_serializing_if = "Option::is_none")]
    pub linked_cpp_server_limit: Option<i32>,
    #[serde(rename = "drawingServerMemory", skip_serializing_if = "Option::is_none")]
    pub drawing_server_memory: Option<i32>,
    #[serde(rename = "cppServerDefaultElementLimit", skip_serializing_if = "Option::is_none")]
    pub cpp_server_default_element_limit: Option<i32>,
    #[serde(rename = "skipRetrievalTest", skip_serializing_if = "Option::is_none")]
    pub skip_retrieval_test: Option<bool>,
}

impl BtDocumentOptionsParams {
    pub fn new() -> BtDocumentOptionsParams {
        BtDocumentOptionsParams {
            cpp_server_memory: None,
            enable_cpp_server_memory_diagnostics: None,
            document_memory: None,
            extended_display_check: None,
            cpp_server_limit: None,
            thumbnail_cpp_server_limit: None,
            linked_cpp_server_limit: None,
            drawing_server_memory: None,
            cpp_server_default_element_limit: None,
            skip_retrieval_test: None,
        }
    }
}


