/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtDocumentInfoAllOf {
    #[serde(rename = "documentThumbnailElementId", skip_serializing_if = "Option::is_none")]
    pub document_thumbnail_element_id: Option<String>,
    #[serde(rename = "duplicateNameViolationError", skip_serializing_if = "Option::is_none")]
    pub duplicate_name_violation_error: Option<String>,
    #[serde(rename = "betaCapabilityIds", skip_serializing_if = "Option::is_none")]
    pub beta_capability_ids: Option<Vec<String>>,
    #[serde(rename = "isUpgradedToLatestVersion", skip_serializing_if = "Option::is_none")]
    pub is_upgraded_to_latest_version: Option<bool>,
}

impl BtDocumentInfoAllOf {
    pub fn new() -> BtDocumentInfoAllOf {
        BtDocumentInfoAllOf {
            document_thumbnail_element_id: None,
            duplicate_name_violation_error: None,
            beta_capability_ids: None,
            is_upgraded_to_latest_version: None,
        }
    }
}


