/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtDocumentSummarySearchInfoAllOf {
    #[serde(rename = "searchHits", skip_serializing_if = "Option::is_none")]
    pub search_hits: Option<Vec<crate::models::BtDocumentSearchHitInfo>>,
}

impl BtDocumentSummarySearchInfoAllOf {
    pub fn new() -> BtDocumentSummarySearchInfoAllOf {
        BtDocumentSummarySearchInfoAllOf {
            search_hits: None,
        }
    }
}


