/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtDocumentElementInfo {
    #[serde(rename = "filename", skip_serializing_if = "Option::is_none")]
    pub filename: Option<String>,
    #[serde(rename = "lengthUnits", skip_serializing_if = "Option::is_none")]
    pub length_units: Option<String>,
    #[serde(rename = "angleUnits", skip_serializing_if = "Option::is_none")]
    pub angle_units: Option<String>,
    #[serde(rename = "massUnits", skip_serializing_if = "Option::is_none")]
    pub mass_units: Option<String>,
    #[serde(rename = "thumbnailInfo", skip_serializing_if = "Option::is_none")]
    pub thumbnail_info: Option<crate::models::BtThumbnailInfo>,
    #[serde(rename = "dataType", skip_serializing_if = "Option::is_none")]
    pub data_type: Option<String>,
    #[serde(rename = "thumbnails", skip_serializing_if = "Option::is_none")]
    pub thumbnails: Option<String>,
    #[serde(rename = "microversionId", skip_serializing_if = "Option::is_none")]
    pub microversion_id: Option<String>,
    #[serde(rename = "elementType", skip_serializing_if = "Option::is_none")]
    pub element_type: Option<ElementType>,
    #[serde(rename = "foreignDataId", skip_serializing_if = "Option::is_none")]
    pub foreign_data_id: Option<String>,
    #[serde(rename = "unupdatable", skip_serializing_if = "Option::is_none")]
    pub unupdatable: Option<bool>,
    #[serde(rename = "specifiedUnit", skip_serializing_if = "Option::is_none")]
    pub specified_unit: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
}

impl BtDocumentElementInfo {
    pub fn new() -> BtDocumentElementInfo {
        BtDocumentElementInfo {
            filename: None,
            length_units: None,
            angle_units: None,
            mass_units: None,
            thumbnail_info: None,
            data_type: None,
            thumbnails: None,
            microversion_id: None,
            element_type: None,
            foreign_data_id: None,
            unupdatable: None,
            specified_unit: None,
            name: None,
            id: None,
            _type: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ElementType {
    #[serde(rename = "PARTSTUDIO")]
    PARTSTUDIO,
    #[serde(rename = "ASSEMBLY")]
    ASSEMBLY,
    #[serde(rename = "DRAWING")]
    DRAWING,
    #[serde(rename = "FEATURESTUDIO")]
    FEATURESTUDIO,
    #[serde(rename = "BLOB")]
    BLOB,
    #[serde(rename = "APPLICATION")]
    APPLICATION,
    #[serde(rename = "TABLE")]
    TABLE,
    #[serde(rename = "BILLOFMATERIALS")]
    BILLOFMATERIALS,
    #[serde(rename = "UNKNOWN")]
    UNKNOWN,
}

