/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtExtendTrialParams {
    #[serde(rename = "extensionDays", skip_serializing_if = "Option::is_none")]
    pub extension_days: Option<i32>,
    #[serde(rename = "userId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
}

impl BtExtendTrialParams {
    pub fn new() -> BtExtendTrialParams {
        BtExtendTrialParams {
            extension_days: None,
            user_id: None,
        }
    }
}


