/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtExportModelParams {
    #[serde(rename = "configuration", skip_serializing_if = "Option::is_none")]
    pub configuration: Option<String>,
    #[serde(rename = "workspaceId", skip_serializing_if = "Option::is_none")]
    pub workspace_id: Option<String>,
    #[serde(rename = "elementId", skip_serializing_if = "Option::is_none")]
    pub element_id: Option<String>,
    #[serde(rename = "documentId", skip_serializing_if = "Option::is_none")]
    pub document_id: Option<String>,
    #[serde(rename = "microversion", skip_serializing_if = "Option::is_none")]
    pub microversion: Option<String>,
    #[serde(rename = "linkDocumentId", skip_serializing_if = "Option::is_none")]
    pub link_document_id: Option<String>,
    #[serde(rename = "documentVersionId", skip_serializing_if = "Option::is_none")]
    pub document_version_id: Option<String>,
    #[serde(rename = "linkDocumentWorkspaceId", skip_serializing_if = "Option::is_none")]
    pub link_document_workspace_id: Option<String>,
    #[serde(rename = "sheetMetalFlat", skip_serializing_if = "Option::is_none")]
    pub sheet_metal_flat: Option<bool>,
    #[serde(rename = "includeBendLines", skip_serializing_if = "Option::is_none")]
    pub include_bend_lines: Option<bool>,
    #[serde(rename = "includeSketches", skip_serializing_if = "Option::is_none")]
    pub include_sketches: Option<bool>,
    #[serde(rename = "flatten", skip_serializing_if = "Option::is_none")]
    pub flatten: Option<bool>,
    #[serde(rename = "splinesAsPolylines", skip_serializing_if = "Option::is_none")]
    pub splines_as_polylines: Option<bool>,
    #[serde(rename = "isPartingOut", skip_serializing_if = "Option::is_none")]
    pub is_parting_out: Option<bool>,
    #[serde(rename = "includeBendCenterlines", skip_serializing_if = "Option::is_none")]
    pub include_bend_centerlines: Option<bool>,
    #[serde(rename = "batchFlatPatterns", skip_serializing_if = "Option::is_none")]
    pub batch_flat_patterns: Option<bool>,
    #[serde(rename = "storeInDocument", skip_serializing_if = "Option::is_none")]
    pub store_in_document: Option<bool>,
    #[serde(rename = "fromUserId", skip_serializing_if = "Option::is_none")]
    pub from_user_id: Option<String>,
    #[serde(rename = "cloudStorageAccountId", skip_serializing_if = "Option::is_none")]
    pub cloud_storage_account_id: Option<String>,
    #[serde(rename = "triggerAutoDownload", skip_serializing_if = "Option::is_none")]
    pub trigger_auto_download: Option<bool>,
    #[serde(rename = "includeStd", skip_serializing_if = "Option::is_none")]
    pub include_std: Option<bool>,
    #[serde(rename = "elementIds", skip_serializing_if = "Option::is_none")]
    pub element_ids: Option<String>,
    #[serde(rename = "userId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
    #[serde(rename = "partIds", skip_serializing_if = "Option::is_none")]
    pub part_ids: Option<String>,
    #[serde(rename = "partQuery", skip_serializing_if = "Option::is_none")]
    pub part_query: Option<String>,
    #[serde(rename = "angleTolerance", skip_serializing_if = "Option::is_none")]
    pub angle_tolerance: Option<f64>,
    #[serde(rename = "chordTolerance", skip_serializing_if = "Option::is_none")]
    pub chord_tolerance: Option<f64>,
    #[serde(rename = "maxFacetWidth", skip_serializing_if = "Option::is_none")]
    pub max_facet_width: Option<f64>,
    #[serde(rename = "cloudObjectId", skip_serializing_if = "Option::is_none")]
    pub cloud_object_id: Option<String>,
    #[serde(rename = "emailLink", skip_serializing_if = "Option::is_none")]
    pub email_link: Option<bool>,
    #[serde(rename = "passwordRequired", skip_serializing_if = "Option::is_none")]
    pub password_required: Option<bool>,
    #[serde(rename = "emailSubject", skip_serializing_if = "Option::is_none")]
    pub email_subject: Option<String>,
    #[serde(rename = "emailMessage", skip_serializing_if = "Option::is_none")]
    pub email_message: Option<String>,
    #[serde(rename = "emailTo", skip_serializing_if = "Option::is_none")]
    pub email_to: Option<String>,
    #[serde(rename = "sendCopyToMe", skip_serializing_if = "Option::is_none")]
    pub send_copy_to_me: Option<bool>,
    #[serde(rename = "view", skip_serializing_if = "Option::is_none")]
    pub view: Option<String>,
    #[serde(rename = "scale", skip_serializing_if = "Option::is_none")]
    pub scale: Option<f64>,
    #[serde(rename = "featureIds", skip_serializing_if = "Option::is_none")]
    pub feature_ids: Option<String>,
    #[serde(rename = "destinationName", skip_serializing_if = "Option::is_none")]
    pub destination_name: Option<String>,
    #[serde(rename = "validForDays", skip_serializing_if = "Option::is_none")]
    pub valid_for_days: Option<i32>,
    #[serde(rename = "includeExportIds", skip_serializing_if = "Option::is_none")]
    pub include_export_ids: Option<bool>,
    #[serde(rename = "minFacetWidth", skip_serializing_if = "Option::is_none")]
    pub min_facet_width: Option<f64>,
    #[serde(rename = "resolution", skip_serializing_if = "Option::is_none")]
    pub resolution: Option<String>,
    #[serde(rename = "grouping", skip_serializing_if = "Option::is_none")]
    pub grouping: Option<String>,
    #[serde(rename = "zipSingleFileOutput", skip_serializing_if = "Option::is_none")]
    pub zip_single_file_output: Option<bool>,
    #[serde(rename = "includeForeignData", skip_serializing_if = "Option::is_none")]
    pub include_foreign_data: Option<bool>,
    #[serde(rename = "deepSearchForForeignData", skip_serializing_if = "Option::is_none")]
    pub deep_search_for_foreign_data: Option<bool>,
    #[serde(rename = "includeReleaseManagementData", skip_serializing_if = "Option::is_none")]
    pub include_release_management_data: Option<bool>,
    #[serde(rename = "includeCustomPropertiesData", skip_serializing_if = "Option::is_none")]
    pub include_custom_properties_data: Option<bool>,
    #[serde(rename = "includeCustomProperties", skip_serializing_if = "Option::is_none")]
    pub include_custom_properties: Option<bool>,
    #[serde(rename = "includeItemsData", skip_serializing_if = "Option::is_none")]
    pub include_items_data: Option<bool>,
    #[serde(rename = "includeLinkedDocuments", skip_serializing_if = "Option::is_none")]
    pub include_linked_documents: Option<bool>,
    #[serde(rename = "extractToS3", skip_serializing_if = "Option::is_none")]
    pub extract_to_s3: Option<bool>,
    #[serde(rename = "units", skip_serializing_if = "Option::is_none")]
    pub units: Option<String>,
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<String>,
    #[serde(rename = "format", skip_serializing_if = "Option::is_none")]
    pub format: Option<String>,
}

impl BtExportModelParams {
    pub fn new() -> BtExportModelParams {
        BtExportModelParams {
            configuration: None,
            workspace_id: None,
            element_id: None,
            document_id: None,
            microversion: None,
            link_document_id: None,
            document_version_id: None,
            link_document_workspace_id: None,
            sheet_metal_flat: None,
            include_bend_lines: None,
            include_sketches: None,
            flatten: None,
            splines_as_polylines: None,
            is_parting_out: None,
            include_bend_centerlines: None,
            batch_flat_patterns: None,
            store_in_document: None,
            from_user_id: None,
            cloud_storage_account_id: None,
            trigger_auto_download: None,
            include_std: None,
            element_ids: None,
            user_id: None,
            part_ids: None,
            part_query: None,
            angle_tolerance: None,
            chord_tolerance: None,
            max_facet_width: None,
            cloud_object_id: None,
            email_link: None,
            password_required: None,
            email_subject: None,
            email_message: None,
            email_to: None,
            send_copy_to_me: None,
            view: None,
            scale: None,
            feature_ids: None,
            destination_name: None,
            valid_for_days: None,
            include_export_ids: None,
            min_facet_width: None,
            resolution: None,
            grouping: None,
            zip_single_file_output: None,
            include_foreign_data: None,
            deep_search_for_foreign_data: None,
            include_release_management_data: None,
            include_custom_properties_data: None,
            include_custom_properties: None,
            include_items_data: None,
            include_linked_documents: None,
            extract_to_s3: None,
            units: None,
            password: None,
            version: None,
            mode: None,
            format: None,
        }
    }
}


