/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtExportModelBody {
    #[serde(rename = "faces", skip_serializing_if = "Option::is_none")]
    pub faces: Option<Vec<crate::models::BtExportModelFace>>,
    #[serde(rename = "vertices", skip_serializing_if = "Option::is_none")]
    pub vertices: Option<Vec<crate::models::BtExportModelVertex>>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<Type>,
    #[serde(rename = "edges", skip_serializing_if = "Option::is_none")]
    pub edges: Option<Vec<crate::models::BtExportModelEdge>>,
}

impl BtExportModelBody {
    pub fn new() -> BtExportModelBody {
        BtExportModelBody {
            faces: None,
            vertices: None,
            id: None,
            _type: None,
            edges: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "SOLID")]
    SOLID,
    #[serde(rename = "SURFACE")]
    SURFACE,
    #[serde(rename = "UNKNOWN")]
    UNKNOWN,
}

