/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtFolderInfoAllOf {
    #[serde(rename = "parentId", skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<String>,
    #[serde(rename = "permissionSet", skip_serializing_if = "Option::is_none")]
    pub permission_set: Option<serde_json::Value>,
    #[serde(rename = "trash", skip_serializing_if = "Option::is_none")]
    pub trash: Option<bool>,
    #[serde(rename = "canUnshare", skip_serializing_if = "Option::is_none")]
    pub can_unshare: Option<bool>,
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    #[serde(rename = "trashedAt", skip_serializing_if = "Option::is_none")]
    pub trashed_at: Option<String>,
    #[serde(rename = "isOrphaned", skip_serializing_if = "Option::is_none")]
    pub is_orphaned: Option<bool>,
}

impl BtFolderInfoAllOf {
    pub fn new() -> BtFolderInfoAllOf {
        BtFolderInfoAllOf {
            parent_id: None,
            permission_set: None,
            trash: None,
            can_unshare: None,
            active: None,
            trashed_at: None,
            is_orphaned: None,
        }
    }
}


