/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtGraphicsAppearance {
    #[serde(rename = "nonTrivial", skip_serializing_if = "Option::is_none")]
    pub non_trivial: Option<bool>,
    #[serde(rename = "reset", skip_serializing_if = "Option::is_none")]
    pub reset: Option<bool>,
    #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
    pub color: Option<Vec<String>>,
    #[serde(rename = "opacity", skip_serializing_if = "Option::is_none")]
    pub opacity: Option<i32>,
}

impl BtGraphicsAppearance {
    pub fn new() -> BtGraphicsAppearance {
        BtGraphicsAppearance {
            non_trivial: None,
            reset: None,
            color: None,
            opacity: None,
        }
    }
}


