/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtGlobalTreeNodeInfoListBtGlobalTreeNodeInfo {
}

impl BtGlobalTreeNodeInfoListBtGlobalTreeNodeInfo {
    pub fn new() -> BtGlobalTreeNodeInfoListBtGlobalTreeNodeInfo {
        BtGlobalTreeNodeInfoListBtGlobalTreeNodeInfo {
        }
    }
}


