/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtGlobalTreeMagicNodeInfoAllOf {
    #[serde(rename = "subType", skip_serializing_if = "Option::is_none")]
    pub sub_type: Option<i32>,
}

impl BtGlobalTreeMagicNodeInfoAllOf {
    pub fn new() -> BtGlobalTreeMagicNodeInfoAllOf {
        BtGlobalTreeMagicNodeInfoAllOf {
            sub_type: None,
        }
    }
}


