/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtIdTranslationInfo {
    #[serde(rename = "elementId", skip_serializing_if = "Option::is_none")]
    pub element_id: Option<String>,
    #[serde(rename = "documentId", skip_serializing_if = "Option::is_none")]
    pub document_id: Option<String>,
    #[serde(rename = "sourceDocumentMicroversion", skip_serializing_if = "Option::is_none")]
    pub source_document_microversion: Option<String>,
    #[serde(rename = "ids", skip_serializing_if = "Option::is_none")]
    pub ids: Option<Vec<crate::models::BtIdTranslationResultInfo>>,
    #[serde(rename = "targetDocumentMicroversion", skip_serializing_if = "Option::is_none")]
    pub target_document_microversion: Option<String>,
}

impl BtIdTranslationInfo {
    pub fn new() -> BtIdTranslationInfo {
        BtIdTranslationInfo {
            element_id: None,
            document_id: None,
            source_document_microversion: None,
            ids: None,
            target_document_microversion: None,
        }
    }
}


