/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtLoginTotpParams {
    #[serde(rename = "totp", skip_serializing_if = "Option::is_none")]
    pub totp: Option<String>,
}

impl BtLoginTotpParams {
    pub fn new() -> BtLoginTotpParams {
        BtLoginTotpParams {
            totp: None,
        }
    }
}


