/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtMetricsListParams {
    #[serde(rename = "collectedMetrics", skip_serializing_if = "Option::is_none")]
    pub collected_metrics: Option<Vec<crate::models::BtMetricParams>>,
}

impl BtMetricsListParams {
    pub fn new() -> BtMetricsListParams {
        BtMetricsListParams {
            collected_metrics: None,
        }
    }
}


