/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtMoveElementInfo {
    #[serde(rename = "errorMessage", skip_serializing_if = "Option::is_none")]
    pub error_message: Option<String>,
    #[serde(rename = "elementOriginalToNewMap", skip_serializing_if = "Option::is_none")]
    pub element_original_to_new_map: Option<::std::collections::HashMap<String, String>>,
    #[serde(rename = "newDocumentId", skip_serializing_if = "Option::is_none")]
    pub new_document_id: Option<String>,
    #[serde(rename = "newWorkspaceId", skip_serializing_if = "Option::is_none")]
    pub new_workspace_id: Option<String>,
    #[serde(rename = "isNewDocument", skip_serializing_if = "Option::is_none")]
    pub is_new_document: Option<bool>,
    #[serde(rename = "newDocumentName", skip_serializing_if = "Option::is_none")]
    pub new_document_name: Option<String>,
    #[serde(rename = "newDocumentVersionId", skip_serializing_if = "Option::is_none")]
    pub new_document_version_id: Option<String>,
}

impl BtMoveElementInfo {
    pub fn new() -> BtMoveElementInfo {
        BtMoveElementInfo {
            error_message: None,
            element_original_to_new_map: None,
            new_document_id: None,
            new_workspace_id: None,
            is_new_document: None,
            new_document_name: None,
            new_document_version_id: None,
        }
    }
}


