/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtMetricParams {
    #[serde(rename = "eventType", skip_serializing_if = "Option::is_none")]
    pub event_type: Option<i32>,
    #[serde(rename = "eventName", skip_serializing_if = "Option::is_none")]
    pub event_name: Option<String>,
    #[serde(rename = "eventNamespace", skip_serializing_if = "Option::is_none")]
    pub event_namespace: Option<String>,
    #[serde(rename = "eventTime", skip_serializing_if = "Option::is_none")]
    pub event_time: Option<String>,
    #[serde(rename = "elementId", skip_serializing_if = "Option::is_none")]
    pub element_id: Option<String>,
    #[serde(rename = "documentId", skip_serializing_if = "Option::is_none")]
    pub document_id: Option<String>,
    #[serde(rename = "systemId", skip_serializing_if = "Option::is_none")]
    pub system_id: Option<String>,
    #[serde(rename = "propertyMap", skip_serializing_if = "Option::is_none")]
    pub property_map: Option<::std::collections::HashMap<String, serde_json::Value>>,
}

impl BtMetricParams {
    pub fn new() -> BtMetricParams {
        BtMetricParams {
            event_type: None,
            event_name: None,
            event_namespace: None,
            event_time: None,
            element_id: None,
            document_id: None,
            system_id: None,
            property_map: None,
        }
    }
}


