/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtNodeReference {
    #[serde(rename = "nodeId", skip_serializing_if = "Option::is_none")]
    pub node_id: Option<String>,
    #[serde(rename = "nodeIdRaw", skip_serializing_if = "Option::is_none")]
    pub node_id_raw: Option<crate::models::BtObjectId>,
}

impl BtNodeReference {
    pub fn new() -> BtNodeReference {
        BtNodeReference {
            node_id: None,
            node_id_raw: None,
        }
    }
}


