/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtPublishWorkflowParams {
    #[serde(rename = "workflowType", skip_serializing_if = "Option::is_none")]
    pub workflow_type: Option<i32>,
    #[serde(rename = "workspaceId", skip_serializing_if = "Option::is_none")]
    pub workspace_id: Option<String>,
    #[serde(rename = "elementId", skip_serializing_if = "Option::is_none")]
    pub element_id: Option<String>,
    #[serde(rename = "documentId", skip_serializing_if = "Option::is_none")]
    pub document_id: Option<String>,
    #[serde(rename = "isObsoletion", skip_serializing_if = "Option::is_none")]
    pub is_obsoletion: Option<bool>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl BtPublishWorkflowParams {
    pub fn new() -> BtPublishWorkflowParams {
        BtPublishWorkflowParams {
            workflow_type: None,
            workspace_id: None,
            element_id: None,
            document_id: None,
            is_obsoletion: None,
            name: None,
            description: None,
        }
    }
}


