/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtPurchaseUserParams {
    #[serde(rename = "consumedQuantity", skip_serializing_if = "Option::is_none")]
    pub consumed_quantity: Option<i32>,
    #[serde(rename = "purchaseId", skip_serializing_if = "Option::is_none")]
    pub purchase_id: Option<String>,
    #[serde(rename = "userId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
}

impl BtPurchaseUserParams {
    pub fn new() -> BtPurchaseUserParams {
        BtPurchaseUserParams {
            consumed_quantity: None,
            purchase_id: None,
            user_id: None,
        }
    }
}


