/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtPartIdParams {
    #[serde(rename = "configuration", skip_serializing_if = "Option::is_none")]
    pub configuration: Option<String>,
    #[serde(rename = "linkDocumentId", skip_serializing_if = "Option::is_none")]
    pub link_document_id: Option<String>,
    #[serde(rename = "ids", skip_serializing_if = "Option::is_none")]
    pub ids: Option<Vec<String>>,
}

impl BtPartIdParams {
    pub fn new() -> BtPartIdParams {
        BtPartIdParams {
            configuration: None,
            link_document_id: None,
            ids: None,
        }
    }
}


