/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtRbacPermissionSchemeParams {
    #[serde(rename = "permissionMap", skip_serializing_if = "Option::is_none")]
    pub permission_map: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl BtRbacPermissionSchemeParams {
    pub fn new() -> BtRbacPermissionSchemeParams {
        BtRbacPermissionSchemeParams {
            permission_map: None,
            name: None,
            description: None,
        }
    }
}


