/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtStandardContentParams {
    #[serde(rename = "parametersId", skip_serializing_if = "Option::is_none")]
    pub parameters_id: Option<String>,
    #[serde(rename = "parametersIdVersion", skip_serializing_if = "Option::is_none")]
    pub parameters_id_version: Option<String>,
    #[serde(rename = "targetDocumentId", skip_serializing_if = "Option::is_none")]
    pub target_document_id: Option<String>,
    #[serde(rename = "targetElementId", skip_serializing_if = "Option::is_none")]
    pub target_element_id: Option<String>,
    #[serde(rename = "saveCustomProperties", skip_serializing_if = "Option::is_none")]
    pub save_custom_properties: Option<bool>,
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<Vec<crate::models::BtStandardContentParameterDefinition>>,
}

impl BtStandardContentParams {
    pub fn new() -> BtStandardContentParams {
        BtStandardContentParams {
            parameters_id: None,
            parameters_id_version: None,
            target_document_id: None,
            target_element_id: None,
            save_custom_properties: None,
            parameters: None,
        }
    }
}


