/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtSendGridDeliveryEventParams {
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "smtpid", skip_serializing_if = "Option::is_none")]
    pub smtpid: Option<String>,
    #[serde(rename = "event", skip_serializing_if = "Option::is_none")]
    pub event: Option<String>,
    #[serde(rename = "ip", skip_serializing_if = "Option::is_none")]
    pub ip: Option<String>,
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<i64>,
}

impl BtSendGridDeliveryEventParams {
    pub fn new() -> BtSendGridDeliveryEventParams {
        BtSendGridDeliveryEventParams {
            email: None,
            smtpid: None,
            event: None,
            ip: None,
            timestamp: None,
        }
    }
}


