/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtStandardContentParameterDefinition {
    #[serde(rename = "visible", skip_serializing_if = "Option::is_none")]
    pub visible: Option<bool>,
    #[serde(rename = "parameterId", skip_serializing_if = "Option::is_none")]
    pub parameter_id: Option<String>,
    #[serde(rename = "isCustomParameter", skip_serializing_if = "Option::is_none")]
    pub is_custom_parameter: Option<bool>,
    #[serde(rename = "isDrivingConfiguration", skip_serializing_if = "Option::is_none")]
    pub is_driving_configuration: Option<bool>,
    #[serde(rename = "defaultValue", skip_serializing_if = "Option::is_none")]
    pub default_value: Option<String>,
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
}

impl BtStandardContentParameterDefinition {
    pub fn new() -> BtStandardContentParameterDefinition {
        BtStandardContentParameterDefinition {
            visible: None,
            parameter_id: None,
            is_custom_parameter: None,
            is_driving_configuration: None,
            default_value: None,
            display_name: None,
        }
    }
}


