/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtStandardContentHierarchyInfo {
    #[serde(rename = "types", skip_serializing_if = "Option::is_none")]
    pub types: Option<String>,
    #[serde(rename = "documentType", skip_serializing_if = "Option::is_none")]
    pub document_type: Option<i32>,
    #[serde(rename = "productionVersionId", skip_serializing_if = "Option::is_none")]
    pub production_version_id: Option<String>,
    #[serde(rename = "testVersionId", skip_serializing_if = "Option::is_none")]
    pub test_version_id: Option<String>,
    #[serde(rename = "defaultWorkspace", skip_serializing_if = "Option::is_none")]
    pub default_workspace: Option<String>,
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    #[serde(rename = "existingVersions", skip_serializing_if = "Option::is_none")]
    pub existing_versions: Option<Vec<crate::models::VersionSpecs>>,
    #[serde(rename = "standard", skip_serializing_if = "Option::is_none")]
    pub standard: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
    #[serde(rename = "href", skip_serializing_if = "Option::is_none")]
    pub href: Option<String>,
    #[serde(rename = "viewRef", skip_serializing_if = "Option::is_none")]
    pub view_ref: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

impl BtStandardContentHierarchyInfo {
    pub fn new() -> BtStandardContentHierarchyInfo {
        BtStandardContentHierarchyInfo {
            types: None,
            document_type: None,
            production_version_id: None,
            test_version_id: None,
            default_workspace: None,
            category: None,
            existing_versions: None,
            standard: None,
            _type: None,
            href: None,
            view_ref: None,
            name: None,
            id: None,
        }
    }
}


