/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtThumbnailInfo {
    #[serde(rename = "sizes", skip_serializing_if = "Option::is_none")]
    pub sizes: Option<Vec<crate::models::BtThumbnailSizeInfo>>,
    #[serde(rename = "secondarySizes", skip_serializing_if = "Option::is_none")]
    pub secondary_sizes: Option<Vec<Vec<crate::models::BtThumbnailSizeInfo>>>,
    #[serde(rename = "href", skip_serializing_if = "Option::is_none")]
    pub href: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

impl BtThumbnailInfo {
    pub fn new() -> BtThumbnailInfo {
        BtThumbnailInfo {
            sizes: None,
            secondary_sizes: None,
            href: None,
            id: None,
        }
    }
}


