/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtTranslationRequestInfo {
    #[serde(rename = "resultWorkspaceId", skip_serializing_if = "Option::is_none")]
    pub result_workspace_id: Option<String>,
    #[serde(rename = "versionId", skip_serializing_if = "Option::is_none")]
    pub version_id: Option<String>,
    #[serde(rename = "workspaceId", skip_serializing_if = "Option::is_none")]
    pub workspace_id: Option<String>,
    #[serde(rename = "documentId", skip_serializing_if = "Option::is_none")]
    pub document_id: Option<String>,
    #[serde(rename = "resultElementIds", skip_serializing_if = "Option::is_none")]
    pub result_element_ids: Option<Vec<String>>,
    #[serde(rename = "resultDocumentId", skip_serializing_if = "Option::is_none")]
    pub result_document_id: Option<String>,
    #[serde(rename = "failureReason", skip_serializing_if = "Option::is_none")]
    pub failure_reason: Option<String>,
    #[serde(rename = "requestState", skip_serializing_if = "Option::is_none")]
    pub request_state: Option<RequestState>,
    #[serde(rename = "requestElementId", skip_serializing_if = "Option::is_none")]
    pub request_element_id: Option<String>,
    #[serde(rename = "resultExternalDataIds", skip_serializing_if = "Option::is_none")]
    pub result_external_data_ids: Option<Vec<String>>,
    #[serde(rename = "href", skip_serializing_if = "Option::is_none")]
    pub href: Option<String>,
    #[serde(rename = "viewRef", skip_serializing_if = "Option::is_none")]
    pub view_ref: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

impl BtTranslationRequestInfo {
    pub fn new() -> BtTranslationRequestInfo {
        BtTranslationRequestInfo {
            result_workspace_id: None,
            version_id: None,
            workspace_id: None,
            document_id: None,
            result_element_ids: None,
            result_document_id: None,
            failure_reason: None,
            request_state: None,
            request_element_id: None,
            result_external_data_ids: None,
            href: None,
            view_ref: None,
            name: None,
            id: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RequestState {
    #[serde(rename = "ACTIVE")]
    ACTIVE,
    #[serde(rename = "DONE")]
    DONE,
    #[serde(rename = "FAILED")]
    FAILED,
}

