/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtToolTreeParams {
    #[serde(rename = "capability", skip_serializing_if = "Option::is_none")]
    pub capability: Option<String>,
    #[serde(rename = "ownerId", skip_serializing_if = "Option::is_none")]
    pub owner_id: Option<String>,
    #[serde(rename = "nodeType", skip_serializing_if = "Option::is_none")]
    pub node_type: Option<i32>,
    #[serde(rename = "useHistory", skip_serializing_if = "Option::is_none")]
    pub use_history: Option<bool>,
    #[serde(rename = "mini", skip_serializing_if = "Option::is_none")]
    pub mini: Option<bool>,
    #[serde(rename = "tooltipKey", skip_serializing_if = "Option::is_none")]
    pub tooltip_key: Option<String>,
    #[serde(rename = "expandedTooltipKey", skip_serializing_if = "Option::is_none")]
    pub expanded_tooltip_key: Option<String>,
    #[serde(rename = "iconInitials", skip_serializing_if = "Option::is_none")]
    pub icon_initials: Option<String>,
    #[serde(rename = "command", skip_serializing_if = "Option::is_none")]
    pub command: Option<String>,
    #[serde(rename = "commandDetails", skip_serializing_if = "Option::is_none")]
    pub command_details: Option<String>,
    #[serde(rename = "featureSpecName", skip_serializing_if = "Option::is_none")]
    pub feature_spec_name: Option<String>,
    #[serde(rename = "fsVersion", skip_serializing_if = "Option::is_none")]
    pub fs_version: Option<i32>,
    #[serde(rename = "isNewerVersionAvailable", skip_serializing_if = "Option::is_none")]
    pub is_newer_version_available: Option<bool>,
    #[serde(rename = "useDynamicSnippet", skip_serializing_if = "Option::is_none")]
    pub use_dynamic_snippet: Option<bool>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "context", skip_serializing_if = "Option::is_none")]
    pub context: Option<i32>,
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<i32>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "signature", skip_serializing_if = "Option::is_none")]
    pub signature: Option<String>,
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    #[serde(rename = "namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
    #[serde(rename = "icon", skip_serializing_if = "Option::is_none")]
    pub icon: Option<String>,
    #[serde(rename = "ownerType", skip_serializing_if = "Option::is_none")]
    pub owner_type: Option<i32>,
}

impl BtToolTreeParams {
    pub fn new() -> BtToolTreeParams {
        BtToolTreeParams {
            capability: None,
            owner_id: None,
            node_type: None,
            use_history: None,
            mini: None,
            tooltip_key: None,
            expanded_tooltip_key: None,
            icon_initials: None,
            command: None,
            command_details: None,
            feature_spec_name: None,
            fs_version: None,
            is_newer_version_available: None,
            use_dynamic_snippet: None,
            name: None,
            context: None,
            priority: None,
            id: None,
            signature: None,
            active: None,
            namespace: None,
            icon: None,
            owner_type: None,
        }
    }
}


