/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtUserAppSettingsParams {
    #[serde(rename = "settings", skip_serializing_if = "Option::is_none")]
    pub settings: Option<Vec<crate::models::BtSettingParam>>,
}

impl BtUserAppSettingsParams {
    pub fn new() -> BtUserAppSettingsParams {
        BtUserAppSettingsParams {
            settings: None,
        }
    }
}


