/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtUpdateWorkflowableTestObjectParams {
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<Vec<crate::models::BtPropertyValueParam>>,
}

impl BtUpdateWorkflowableTestObjectParams {
    pub fn new() -> BtUpdateWorkflowableTestObjectParams {
        BtUpdateWorkflowableTestObjectParams {
            properties: None,
        }
    }
}


