/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtUserAgentVersion {
    #[serde(rename = "patchVersion", skip_serializing_if = "Option::is_none")]
    pub patch_version: Option<i32>,
    #[serde(rename = "majorVersion", skip_serializing_if = "Option::is_none")]
    pub major_version: Option<i32>,
    #[serde(rename = "minorVersion", skip_serializing_if = "Option::is_none")]
    pub minor_version: Option<i32>,
}

impl BtUserAgentVersion {
    pub fn new() -> BtUserAgentVersion {
        BtUserAgentVersion {
            patch_version: None,
            major_version: None,
            minor_version: None,
        }
    }
}


