/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtWorkflowableTestObjectInfo {
    #[serde(rename = "info", skip_serializing_if = "Option::is_none")]
    pub info: Option<::std::collections::HashMap<String, String>>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "companyId", skip_serializing_if = "Option::is_none")]
    pub company_id: Option<String>,
    #[serde(rename = "documentId", skip_serializing_if = "Option::is_none")]
    pub document_id: Option<String>,
    #[serde(rename = "workflow", skip_serializing_if = "Option::is_none")]
    pub workflow: Option<crate::models::BtWorkflowSnapshotInfo>,
    #[serde(rename = "isObsoletion", skip_serializing_if = "Option::is_none")]
    pub is_obsoletion: Option<bool>,
    #[serde(rename = "workflowId", skip_serializing_if = "Option::is_none")]
    pub workflow_id: Option<crate::models::BtPublishedWorkflowId>,
    #[serde(rename = "nameAsProperty", skip_serializing_if = "Option::is_none")]
    pub name_as_property: Option<String>,
    #[serde(rename = "descriptionAsProperty", skip_serializing_if = "Option::is_none")]
    pub description_as_property: Option<String>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<Vec<crate::models::BtWorkflowPropertyInfo>>,
    #[serde(rename = "href", skip_serializing_if = "Option::is_none")]
    pub href: Option<String>,
    #[serde(rename = "viewRef", skip_serializing_if = "Option::is_none")]
    pub view_ref: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

impl BtWorkflowableTestObjectInfo {
    pub fn new() -> BtWorkflowableTestObjectInfo {
        BtWorkflowableTestObjectInfo {
            info: None,
            description: None,
            company_id: None,
            document_id: None,
            workflow: None,
            is_obsoletion: None,
            workflow_id: None,
            name_as_property: None,
            description_as_property: None,
            properties: None,
            href: None,
            view_ref: None,
            name: None,
            id: None,
        }
    }
}


