/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtapiKeyParams {
    #[serde(rename = "companyId", skip_serializing_if = "Option::is_none")]
    pub company_id: Option<String>,
    #[serde(rename = "scopeNames", skip_serializing_if = "Option::is_none")]
    pub scope_names: Option<Vec<String>>,
}

impl BtapiKeyParams {
    pub fn new() -> BtapiKeyParams {
        BtapiKeyParams {
            company_id: None,
            scope_names: None,
        }
    }
}


