/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtpNode {
    #[serde(rename = "atomic", skip_serializing_if = "Option::is_none")]
    pub atomic: Option<bool>,
    #[serde(rename = "shortDescriptor", skip_serializing_if = "Option::is_none")]
    pub short_descriptor: Option<String>,
    #[serde(rename = "startSourceLocation", skip_serializing_if = "Option::is_none")]
    pub start_source_location: Option<i32>,
    #[serde(rename = "endSourceLocation", skip_serializing_if = "Option::is_none")]
    pub end_source_location: Option<i32>,
    #[serde(rename = "documentationType", skip_serializing_if = "Option::is_none")]
    pub documentation_type: Option<DocumentationType>,
    #[serde(rename = "spaceBefore", skip_serializing_if = "Option::is_none")]
    pub space_before: Option<crate::models::BtpSpace>,
    #[serde(rename = "spaceAfter", skip_serializing_if = "Option::is_none")]
    pub space_after: Option<crate::models::BtpSpace>,
    #[serde(rename = "spaceDefault", skip_serializing_if = "Option::is_none")]
    pub space_default: Option<bool>,
    #[serde(rename = "nodeId", skip_serializing_if = "Option::is_none")]
    pub node_id: Option<String>,
}

impl BtpNode {
    pub fn new() -> BtpNode {
        BtpNode {
            atomic: None,
            short_descriptor: None,
            start_source_location: None,
            end_source_location: None,
            documentation_type: None,
            space_before: None,
            space_after: None,
            space_default: None,
            node_id: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DocumentationType {
    #[serde(rename = "FUNCTION")]
    FUNCTION,
    #[serde(rename = "PREDICATE")]
    PREDICATE,
    #[serde(rename = "CONSTANT")]
    CONSTANT,
    #[serde(rename = "ENUM")]
    _ENUM,
    #[serde(rename = "USER_TYPE")]
    USERTYPE,
    #[serde(rename = "FEATURE_DEFINITION")]
    FEATUREDEFINITION,
    #[serde(rename = "FILE_HEADER")]
    FILEHEADER,
    #[serde(rename = "UNDOCUMENTABLE")]
    UNDOCUMENTABLE,
    #[serde(rename = "UNKNOWN")]
    UNKNOWN,
}

