/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtpdmMetadataParams {
    #[serde(rename = "configuration", skip_serializing_if = "Option::is_none")]
    pub configuration: Option<String>,
    #[serde(rename = "elementId", skip_serializing_if = "Option::is_none")]
    pub element_id: Option<String>,
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
    #[serde(rename = "partNumber", skip_serializing_if = "Option::is_none")]
    pub part_number: Option<String>,
    #[serde(rename = "vendor", skip_serializing_if = "Option::is_none")]
    pub vendor: Option<String>,
    #[serde(rename = "productLine", skip_serializing_if = "Option::is_none")]
    pub product_line: Option<String>,
    #[serde(rename = "title1", skip_serializing_if = "Option::is_none")]
    pub title1: Option<String>,
    #[serde(rename = "title2", skip_serializing_if = "Option::is_none")]
    pub title2: Option<String>,
    #[serde(rename = "title3", skip_serializing_if = "Option::is_none")]
    pub title3: Option<String>,
    #[serde(rename = "partId", skip_serializing_if = "Option::is_none")]
    pub part_id: Option<String>,
    #[serde(rename = "customProperties", skip_serializing_if = "Option::is_none")]
    pub custom_properties: Option<Vec<crate::models::BtNameValuePair>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<State>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "revision", skip_serializing_if = "Option::is_none")]
    pub revision: Option<String>,
}

impl BtpdmMetadataParams {
    pub fn new() -> BtpdmMetadataParams {
        BtpdmMetadataParams {
            configuration: None,
            element_id: None,
            project: None,
            part_number: None,
            vendor: None,
            product_line: None,
            title1: None,
            title2: None,
            title3: None,
            part_id: None,
            custom_properties: None,
            name: None,
            id: None,
            state: None,
            description: None,
            revision: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum State {
    #[serde(rename = "IN_PROGRESS")]
    INPROGRESS,
    #[serde(rename = "PENDING")]
    PENDING,
    #[serde(rename = "RELEASED")]
    RELEASED,
    #[serde(rename = "OBSOLETE")]
    OBSOLETE,
    #[serde(rename = "REJECTED")]
    REJECTED,
    #[serde(rename = "DISCARDED")]
    DISCARDED,
}

