/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CloudObjectPathSegment {
    #[serde(rename = "cloudStorageAccountId", skip_serializing_if = "Option::is_none")]
    pub cloud_storage_account_id: Option<String>,
    #[serde(rename = "cloudStorageProviderType", skip_serializing_if = "Option::is_none")]
    pub cloud_storage_provider_type: Option<i32>,
    #[serde(rename = "subType", skip_serializing_if = "Option::is_none")]
    pub sub_type: Option<i32>,
    #[serde(rename = "treeHref", skip_serializing_if = "Option::is_none")]
    pub tree_href: Option<String>,
    #[serde(rename = "resourceType", skip_serializing_if = "Option::is_none")]
    pub resource_type: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

impl CloudObjectPathSegment {
    pub fn new() -> CloudObjectPathSegment {
        CloudObjectPathSegment {
            cloud_storage_account_id: None,
            cloud_storage_provider_type: None,
            sub_type: None,
            tree_href: None,
            resource_type: None,
            name: None,
            id: None,
        }
    }
}


