/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GlobalPermissionInfo {
    #[serde(rename = "adminEnterprise", skip_serializing_if = "Option::is_none")]
    pub admin_enterprise: Option<bool>,
    #[serde(rename = "manageRbac", skip_serializing_if = "Option::is_none")]
    pub manage_rbac: Option<bool>,
    #[serde(rename = "manageUsers", skip_serializing_if = "Option::is_none")]
    pub manage_users: Option<bool>,
    #[serde(rename = "manageGuestUsers", skip_serializing_if = "Option::is_none")]
    pub manage_guest_users: Option<bool>,
    #[serde(rename = "deletePermanently", skip_serializing_if = "Option::is_none")]
    pub delete_permanently: Option<bool>,
    #[serde(rename = "accessReports", skip_serializing_if = "Option::is_none")]
    pub access_reports: Option<bool>,
    #[serde(rename = "createProject", skip_serializing_if = "Option::is_none")]
    pub create_project: Option<bool>,
    #[serde(rename = "approveReleases", skip_serializing_if = "Option::is_none")]
    pub approve_releases: Option<bool>,
    #[serde(rename = "createReleases", skip_serializing_if = "Option::is_none")]
    pub create_releases: Option<bool>,
    #[serde(rename = "shareForAnonymousAccess", skip_serializing_if = "Option::is_none")]
    pub share_for_anonymous_access: Option<bool>,
}

impl GlobalPermissionInfo {
    pub fn new() -> GlobalPermissionInfo {
        GlobalPermissionInfo {
            admin_enterprise: None,
            manage_rbac: None,
            manage_users: None,
            manage_guest_users: None,
            delete_permanently: None,
            access_reports: None,
            create_project: None,
            approve_releases: None,
            create_releases: None,
            share_for_anonymous_access: None,
        }
    }
}


