/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Message {
    #[serde(rename = "defaultTitle", skip_serializing_if = "Option::is_none")]
    pub default_title: Option<String>,
    #[serde(rename = "defaultTemplate", skip_serializing_if = "Option::is_none")]
    pub default_template: Option<String>,
    #[serde(rename = "messageLevel", skip_serializing_if = "Option::is_none")]
    pub message_level: Option<MessageLevel>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

impl Message {
    pub fn new() -> Message {
        Message {
            default_title: None,
            default_template: None,
            message_level: None,
            id: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MessageLevel {
    #[serde(rename = "INFO")]
    INFO,
    #[serde(rename = "WARNING")]
    WARNING,
    #[serde(rename = "ERROR")]
    ERROR,
    #[serde(rename = "MARKETING")]
    MARKETING,
    #[serde(rename = "PRODUCT")]
    PRODUCT,
    #[serde(rename = "IMPORTANT")]
    IMPORTANT,
    #[serde(rename = "ACTION")]
    ACTION,
}

