/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateParams {
    #[serde(rename = "toReference", skip_serializing_if = "Option::is_none")]
    pub to_reference: Option<crate::models::BtUniqueDocumentItemParams>,
    #[serde(rename = "fromReference", skip_serializing_if = "Option::is_none")]
    pub from_reference: Option<crate::models::BtUniqueDocumentItemParams>,
    #[serde(rename = "idsToUpdate", skip_serializing_if = "Option::is_none")]
    pub ids_to_update: Option<Vec<String>>,
}

impl UpdateParams {
    pub fn new() -> UpdateParams {
        UpdateParams {
            to_reference: None,
            from_reference: None,
            ids_to_update: None,
        }
    }
}


