/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * The version of the OpenAPI document: 1.104
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Xml {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
    #[serde(rename = "prefix", skip_serializing_if = "Option::is_none")]
    pub prefix: Option<String>,
    #[serde(rename = "attribute", skip_serializing_if = "Option::is_none")]
    pub attribute: Option<bool>,
    #[serde(rename = "wrapped", skip_serializing_if = "Option::is_none")]
    pub wrapped: Option<bool>,
    #[serde(rename = "extensions", skip_serializing_if = "Option::is_none")]
    pub extensions: Option<::std::collections::HashMap<String, serde_json::Value>>,
}

impl Xml {
    pub fn new() -> Xml {
        Xml {
            name: None,
            namespace: None,
            prefix: None,
            attribute: None,
            wrapped: None,
            extensions: None,
        }
    }
}


